AWSTemplateFormatVersion: 2010-09-09
Description: Build Infrastructure resources for persisting Terrafrom state files

Parameters:  
  Name:
    Description: Name for resource to infra backend
    Type: String
    Default: tf-state
  Env:
    Description: env for infra state
    Type: String
    Default: dev

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Sub ${Env}-${Name}-${AWS::Region}
      Tags:
        - Key: CreatedBy
          Value: Terrafrom

  dynamodbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - 
          AttributeName: LockID
          AttributeType: S
      KeySchema:
        - 
          AttributeName: LockID
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: !Sub ${Env}-${Name}-${AWS::Region}
      Tags:
        - Key: CreatedBy
          Value: Terrafrom
